### ISSUE TITLE
Extra argument 'from' in call

### ISSUE THREAD

**Issue by ityutin** [givip/Telegrammer#24]
Hello! 

First I want to thank you for your amazing library, I find it extremely convenient to work with. 
Now back to my issue. I can't build my project if I use the function below

`self.dispatcher.remove(handler: handler, from: group)`

I get the error
`Error:(76, 60) extra argument 'from' in call`

I can't understand what's wrong with it. `group` variable is correct and has type `HandlerGroup`. I'm using Swift 4.1. Does your project successfully build using the line like this?

Thank you!

**Comment by givip** [comment]
Thanks @ityutin! Please provide me version of Telegrammer.

**Comment by ityutin** [comment]
@givip 0.3.0

**Comment by givip** [comment]
@ityutin I cannot reproduce:
i’ve tryed and compiles succesfully
```swift
let group = HandlerGroup(id: 10, name: "ten")
 
let echoHandler = MessageHandler(filters: Filters.text, callback: echoResponse)
dispatcher.add(handler: echoHandler, to: group)
 
dispatcher.remove(handler: echoHandler, from: group)
```

Please provide demo example.

**Comment by ityutin** [comment]
Hm, it compiles indeed. Then I'm sorry that I bothered you with my spaghetti. I re-checked my code many times before I created the issue. I'm going to find what is wrong with my current code.

**Comment by givip** [comment]
Cannot reproduce

**Comment by ityutin** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1867589/44518451-e7f90600-a6d2-11e8-8663-5392e3137eb6.png">

It's funny. He treats the first function well, but punishes the last one. It can't recognize `remove` function.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/1867589/44518379-c39d2980-a6d2-11e8-9919-f31a6ec0877a.png">

It compiles okay if function has a generic constaint to `Handler`. Otherwise it fails.

**Comment by givip** [comment]
Thanks, I'll check again

**Comment by givip** [comment]
@ityutin thank for reported issue! Reason of this behavior is that `remove` and `add` methods receive concrete objects, that are already conforming to `Handler` protocol. I think this is really bad solution. I'll fix it in next version.
