### ISSUE TITLE
Using the Vapor Template I kinda experience memory leaks which result in a terminating instance.

### ISSUE THREAD

**Issue by Narsail** [givip/Telegrammer#25]
Every time the underlying bot is sending a request - just the standby web hook logic - it increases the memory footprint.

**Comment by givip** [comment]
Telegrammer didn't send requests for web hooks logic, on the contrary, it works as server and waits requests from Telegram server. [Vapor template](https://github.com/givip/telegram-bot-template) uses long polling out of the box. If you are using web hooks, please send me example of leaking code. I have bot on production which use web hooks and for today has 130 days uptime, without leaks.

**Comment by givip** [comment]
I found this leak, when you use Logpolling. Reopening.

**Comment by givip** [comment]
Fixed in 0.4.3
