### ISSUE TITLE
Fail update dependency

### ISSUE THREAD

**Issue by ct4h** [givip/Telegrammer#30]
``swift package generate-xcodeproj`` return error after update to 0.5.4 version.

**Console log:**
````
error: multiple products named 'Logging' in: Console, swift-log
error: multiple targets named 'Logging' in: Console, swift-log
````

**Swift version:**
````
Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
````

**Comment by givip** [comment]
@ct4h Thanks for issue. The reason is `Logging` framework. `Vapor` also use the same name for their own framework. I notified `Vapor` developers, that they use the same namespace as `swift-log`. The only solution for now is to use Telegrammer 0.5.1

**Comment by gentges** [comment]
I changed the following lines in my Package.swift:
```
.package(url: "https://github.com/givip/Telegrammer.git", from: "0.5.2"),
.package(url: "https://github.com/vapor/vapor.git", from: "3.3.0")
```
But I still get the error that @ct4h received.

**Comment by givip** [comment]
Sorry for my mistake @macintosh-HD @ct4h , only version "0.5.1" and previouses will be working with Vapor correctly.
BTW, you should specify exact version in your Package.swift file, like this:
```
.package(url: "https://github.com/givip/Telegrammer.git", .exact("0.5.1")),
.package(url: "https://github.com/vapor/vapor.git", from: "3.3.0")
```

**Comment by gentges** [comment]
Thanks @givip that helped me a lot!
