### ISSUE TITLE
Webhook certificate text instead of file path?

### ISSUE THREAD

**Issue by betzerra** [givip/Telegrammer#31]
First of all, great repo BTW. Thanks for this 🎉 

I noticed that the code is expecting the `pem` certificate's path. 

```
if let publicCert = bot.settings.webhooksPublicCert {
  guard let fileHandle = FileHandle(forReadingAtPath: publicCert) else {
    let errorDescription = "Public key '\(publicCert)' was specified for HTTPS server, but wasn't found"
    log.error(errorDescription.logMessage)
    throw CoreError(identifier: "FileIO", reason: errorDescription)
  }

  cert = InputFile(data: fileHandle.readDataToEndOfFile(), filename: publicCert)
}
```

Since I'm deploying the bot with [Dokku](https://github.com/dokku/dokku), I don't have too much control on the file system (everything running on containers). I was thinking about an option of getting the certficate's content on another environment variable. What do you think?

**Comment by givip** [comment]
Hi! Your welcome, @betzerra 
This is good point, I think this would work. 
If you prepare PR with improvement, I'll include it in version 0.6.0

**Comment by givip** [comment]
Will be released in 0.6.0

**Comment by betzerra** [comment]
Hey sorry about the delay. 
I tried to make it work, but I wasn't able to setup my webhooks correclty 😞.

I'll ping you if I try again later and succeed.

**Comment by betzerra** [comment]
OH! You did it here https://github.com/givip/Telegrammer/commit/8360e851fb96970d4bafcf4122a9c37f85d5be01

Kudos!
