### ISSUE TITLE
Supporting Swift 5.1 and Vapor 4

### ISSUE THREAD

**Issue by ts95** [givip/Telegrammer#37]
Vapor 4 is in the making ([v4.0.0-alpha.3.2](https://github.com/vapor/vapor/tree/4.0.0-alpha.3.2)) and will leverage [new features in Swift 5.1](https://www.hackingwithswift.com/articles/182/whats-new-in-swift-5-1). I think it would be a good idea to start working on a new Vapor template as well as updating the library to use Swift 5.1 and its new features.

**Comment by givip** [comment]
Implemented in 1.0.0-alpha.2
