### ISSUE TITLE
Crash on using combined filters (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by on123** [givip/Telegrammer#42]
When using a combined filter in a telegrammer-vapor-middleware based app like so (here a 'not'):

```
        let answerHandler = MessageHandler(filters: !Filters.command,
                                           callback: answerResponse)
        dispatcher.add(handler: answerHandler,to: HandlerGroup.answers)


```
it results in the following crash on an incoming update:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/794440/75811268-66386d00-5d8c-11ea-9c31-e78fc1a684cd.png">

Not only for the logical not (!), but same result for other logical operations (like and: &&, or: ||)
Without logical operations it works like expected.

**Comment by givip** [comment]
Fix here, try to check https://github.com/givip/Telegrammer/commit/32657287befddf3d303287bf319901f5c7a6f24e
